#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(readlink -f $(dirname $0))
IMAGE_DIR=$SCRIPT_DIR/../image

DIR=chroot
RELEASE=jammy
APPS=vim,openssh-server

sudo rm -rf $DIR
sudo mkdir -p $DIR
sudo chmod 0755 $DIR

sudo debootstrap --arch=amd64 --include=$APPS $RELEASE $DIR https://mirrors.tuna.tsinghua.edu.cn/ubuntu/

# Set some defaults and enable promtless ssh to the machine for root.
sudo sed -i '/^root/ { s/:x:/::/ }' $DIR/etc/passwd
echo 'T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100' | sudo tee -a $DIR/etc/inittab
printf '[Match]\nName=eth0\n\n[Network]\nDHCP=yes\n' | sudo tee -a $DIR/etc/systemd/network/99-eth0_default.network
echo '/dev/root / ext4 defaults 0 0' | sudo tee -a $DIR/etc/fstab
echo 'debugfs /sys/kernel/debug debugfs defaults 0 0' | sudo tee -a $DIR/etc/fstab
echo 'configfs /sys/kernel/config/ configfs defaults 0 0' | sudo tee -a $DIR/etc/fstab
echo 'binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc defaults 0 0' | sudo tee -a $DIR/etc/fstab
echo -en "127.0.0.1\tlocalhost\n" | sudo tee $DIR/etc/hosts
echo "nameserver 8.8.8.8" | sudo tee -a $DIR/etc/resolve.conf
echo "ubuntu" | sudo tee $DIR/etc/hostname
# ssh-keygen -f $RELEASE.id_rsa -t rsa -N ''
# sudo mkdir -p $DIR/root/.ssh/
# cat $RELEASE.id_rsa.pub | sudo tee $DIR/root/.ssh/authorized_keys

# Add udev rules for custom drivers.
# Create a /dev/vim2m symlink for the device managed by the vim2m driver
echo 'ATTR{name}=="vim2m", SYMLINK+="vim2m"' | sudo tee -a $DIR/etc/udev/rules.d/50-udev-default.rules

# Build a disk image
mkdir -p $IMAGE_DIR

dd if=/dev/zero of=$IMAGE_DIR/$RELEASE.img bs=1M seek=$((1024 * 32)) count=1
sudo mkfs.ext4 -F $IMAGE_DIR/$RELEASE.img
sudo mkdir -p /mnt/$DIR
sudo mount -o loop $IMAGE_DIR/$RELEASE.img /mnt/$DIR
sudo cp -a $DIR/. /mnt/$DIR/.
sudo umount /mnt/$DIR

sudo rm -rf $DIR
